firebase deploy
=== Deploying to 'founders-feedback'...

i  deploying firestore, functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

/home/user/studio/functions/src/index.ts
  10:9   warning  'onRequest' is defined but never used  @typescript-eslint/no-unused-vars
  11:13  warning  'logger' is defined but never used     @typescript-eslint/no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

src/index.ts:10:1 - error TS6133: 'onRequest' is declared but its value is never read.

10 import {onRequest} from "firebase-functions/v2/https";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:11:1 - error TS6133: 'logger' is declared but its value is never read.

11 import * as logger from "firebase-functions/logger";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/index.ts:10

Error: functions predeploy error: Command terminated with non-zero exit code 2

Why aren't these functions being used yet?